# fly.toml app configuration file generated for studyai on 2023-05-20T02:20:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "studyai"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
